### ISSUE TITLE
PicasaService.Insert for photo upload doesn't work on Mono

### ISSUE THREAD

**Issue by GoogleCodeExporter** [WhatSupYap/google-gdata#241]
```
When trying to upload a photo with PicasaService.Insert() it just hangs 
and after a couple of minutes dies with the following exception (tested 
both with Mono 2.4 and Mono SVN HEAD):

Google.GData.Client.GDataRequestException: Execution of request failed:
http://picasaweb.google.com/data/feed/api/user/SECRET/SECRET/SECRET --->
System.Net.WebException: Error getting response stream (ReadDone2):
ReceiveFailure ---> System.Exception:    at
System.Net.WebConnection.HandleError(WebExceptionStatus st, 
System.Exception e,
System.String where)
   at System.Net.WebConnection.ReadDone(IAsyncResult result)
   at System.Net.Sockets.Socket+SocketAsyncResult.Complete()
   at System.Net.Sockets.Socket+Worker.Receive()
  at System.Net.WebConnection.HandleError (WebExceptionStatus st,
System.Exception e, System.String where) [0x00000] 
  --- End of inner exception stack trace ---
  at System.Net.HttpWebRequest.EndGetResponse (IAsyncResult asyncResult)
[0x00000] 
  at System.Net.HttpWebRequest.GetResponse () [0x00000] 
  at Google.GData.Client.GDataRequest.Execute () [0x00000] 
  --- End of inner exception stack trace ---
  at Google.GData.Client.GDataRequest.Execute () [0x00000] 
  at Google.GData.Client.GDataGAuthRequest.Execute (Int32 retryCounter)
[0x00000]
```

Original issue reported on code.google.com by `ivan.nik...@gmail.com` on 20 Apr 2009 at 7:30

**Comment by GoogleCodeExporter** [comment]
```
can not reproduce this. I have unit tests that insert photos and they work just 
fine with mono 2.4. I need more 
detail to start working on this.



```

Original comment by `fman...@gmail.com` on 23 Apr 2009 at 4:05
- Changed state: **Reviewed**

**Comment by GoogleCodeExporter** [comment]
```
I can reproduce with the attached minimal test case. Compile with "make" and run
bin/Test.exe . Note that you have to set username/password in Test.cs before 
compiling.
```

Original comment by `ivan.nik...@gmail.com` on 29 Apr 2009 at 10:04

Attachments:
- [test-case-issue-241.zip](https://storage.googleapis.com/google-code-attachments/google-gdata/issue-241/comment-2/test-case-issue-241.zip)

**Comment by GoogleCodeExporter** [comment]
```
what platform is this runing on? This works fine with Mono 2.4 under Mac. 
```

Original comment by `fman...@gmail.com` on 30 Apr 2009 at 11:46

**Comment by GoogleCodeExporter** [comment]
```
It's running on Linux, but I get the same with Mono on windows in a VM. I 
suspect
there might be a networking issue involved then since I asked a friend on Linux 
to
test and it works fine for him. I suppose you can close this bug as invalid 
then.
```

Original comment by `ivan.nik...@gmail.com` on 30 Apr 2009 at 3:35

**Comment by GoogleCodeExporter** [comment]
```
Same as 240
```

Original comment by `fman...@gmail.com` on 13 May 2009 at 10:17
- Changed state: **Invalid**
