### ISSUE TITLE
Blogger demo (.Net version) is throwing WebException while posting : "The remote server returned an error: (405) Method Not Allowed."

### ISSUE THREAD

**Issue by GoogleCodeExporter** [WhatSupYap/google-gdata#246]
```
What steps will reproduce the problem?
1. Login into Blogger Demo (.Net windows app sample)
2. Click GO button to retrieve blogs
3. Click ADD button to add entry
4. Click OK button after adding Title & Description in addentry form
5. After some time an unhandled exception box is popping out saying,

Execution of request failed:
http://rapidmovieshare.blogspot.com/feeds/posts/default

What is the expected output? What do you see instead?

Instead of posting the entry into the blog an unhandled exception box is 
coming out with the following details:

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
Google.GData.Client.GDataRequestException: Execution of request failed: 
http://rapidmovieshare.blogspot.com/feeds/posts/default ---> 
System.Net.WebException: The remote server returned an error: (405) Method 
Not Allowed.
   at System.Net.HttpWebRequest.GetResponse()
   at Google.GData.Client.GDataRequest.Execute()
   --- End of inner exception stack trace ---
   at Google.GData.Client.GDataRequest.Execute()
   at Google.GData.Client.GDataGAuthRequest.Execute(Int32 retryCounter)
   at Google.GData.Client.GDataGAuthRequest.Execute()
   at Google.GData.Client.Service.EntrySend(Uri feedUri, AtomBase 
baseEntry, GDataRequestType type, AsyncSendData data)
   at Google.GData.Client.Service.Insert(Uri feedUri, AtomEntry newEntry, 
AsyncSendData data)
   at Google.GData.Client.Service.Insert[TEntry](Uri feedUri, TEntry entry)
   at Blogger.Blogger.AddEntry_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons 
button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& 
m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, 
IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.3053 (netfxsp.050727-3000)
    CodeBase: 
file:///C:/Windows/Microsoft.NET/Framework/v2.0.50727/mscorlib.dll
----------------------------------------
Blogger
    Assembly Version: 1.4.0.2
    Win32 Version: 1.4.0.2
    CodeBase: file:///E:/Google/Google%20Data%20API%
20SDK/Samples/Blogger.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.3053 (netfxsp.050727-3000)
    CodeBase: 
file:///C:/Windows/assembly/GAC_MSIL/System.Windows.Forms/2.0.0.0__b77a5c56
1934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.3053 (netfxsp.050727-3000)
    CodeBase: 
file:///C:/Windows/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/Syste
m.dll
----------------------------------------
System.Drawing
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.3053 (netfxsp.050727-3000)
    CodeBase: 
file:///C:/Windows/assembly/GAC_MSIL/System.Drawing/2.0.0.0__b03f5f7f11d50a
3a/System.Drawing.dll
----------------------------------------
Google.GData.Client
    Assembly Version: 1.4.0.2
    Win32 Version: 1.4.0.2
    CodeBase: file:///E:/Google/Google%20Data%20API%
20SDK/Samples/Google.GData.Client.DLL
----------------------------------------
System.Web
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.3053 (netfxsp.050727-3000)
    CodeBase: 
file:///C:/Windows/assembly/GAC_32/System.Web/2.0.0.0__b03f5f7f11d50a3a/Sys
tem.Web.dll
----------------------------------------
System.Configuration
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.3053 (netfxsp.050727-3000)
    CodeBase: 
file:///C:/Windows/assembly/GAC_MSIL/System.Configuration/2.0.0.0__b03f5f7f
11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.3053 (netfxsp.050727-3000)
    CodeBase: 
file:///C:/Windows/assembly/GAC_MSIL/System.Xml/2.0.0.0__b77a5c561934e089/S
ystem.Xml.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.


What version of the product are you using? On what operating system?

Details as follows:

.Net framework : 3.5 sp1
Google API SDK : 1.4.0.2
Operating System : Vista Home Premium SP1
Visual Studio : 2008 sp1

Please provide any additional information below.

```

Original issue reported on code.google.com by `anidotNET` on 8 May 2009 at 7:08

**Comment by GoogleCodeExporter** [comment]
```
Not reproducable for me. I do get an error, and i think i need to check what 
that is (service related in m case), 
but i get a 201 created back from the service. Are you logged in correctly? Can 
you catch what is send over the 
wire? 
```

Original comment by `fman...@gmail.com` on 13 May 2009 at 2:11
- Changed state: **Verified**

**Comment by GoogleCodeExporter** [comment]
```
Yes ofcourse I logged in correctly. I was trying it on only one blog 
("rapidmovieshare.blogspot.com") every time. One more thing is that when I 
selected 
this blog in the first form nothing was coming up in the FeedView (TreeView) 
control, 
but already many posts are there in that particular blog though it did not show 
up in 
the app.

After that I tried this app on a different blog. Here FeedView was showing all 
the 
posts, but when I tried to post something using addentry form I got a different 
exception everytime. The exception details is as follows:

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
Google.GData.Client.ClientFeedException: Parsing failed ---> 
System.Xml.XmlException: 
Root element is missing.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ThrowWithoutLineInfo(String res)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlTextReader.Read()
   at Google.GData.Client.BaseFeedParser.MoveToStartElement(XmlReader reader)
   at Google.GData.Client.AtomFeedParser.Parse(Stream streamInput, AtomFeed feed)
   --- End of inner exception stack trace ---
   at Google.GData.Client.AtomFeedParser.Parse(Stream streamInput, AtomFeed feed)
   at Google.GData.Client.AtomFeed.Parse(Stream stream, AlternativeFormat format)
   at Google.GData.Client.Service.CreateAndParseFeed(Stream inputStream, Uri 
uriToUse)
   at Google.GData.Client.Service.CreateAndParseEntry(Stream inputStream, Uri 
uriTarget)
   at Google.GData.Client.Service.Insert(Uri feedUri, AtomEntry newEntry, 
AsyncSendData data)
   at Google.GData.Client.Service.Insert[TEntry](Uri feedUri, TEntry entry)
   at Blogger.Blogger.AddEntry_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 
clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr 
wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.3053 (netfxsp.050727-3000)
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v2.0.50727/mscorlib.dll
----------------------------------------
Blogger
    Assembly Version: 1.4.0.2
    Win32 Version: 1.4.0.2
    CodeBase: file:///E:/Google/Google%20Data%20API%20SDK/Samples/Blogger.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.3053 (netfxsp.050727-3000)
    CodeBase: 
file:///C:/Windows/assembly/GAC_MSIL/System.Windows.Forms/2.0.0.0__b77a5c561934e
089/S
ystem.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.3053 (netfxsp.050727-3000)
    CodeBase: 
file:///C:/Windows/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.3053 (netfxsp.050727-3000)
    CodeBase: 
file:///C:/Windows/assembly/GAC_MSIL/System.Drawing/2.0.0.0__b03f5f7f11d50a3a/Sy
stem.
Drawing.dll
----------------------------------------
Google.GData.Client
    Assembly Version: 1.4.0.2
    Win32 Version: 1.4.0.2
    CodeBase: 
file:///E:/Google/Google%20Data%20API%20SDK/Samples/Google.GData.Client.DLL
----------------------------------------
System.Web
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.3053 (netfxsp.050727-3000)
    CodeBase: 
file:///C:/Windows/assembly/GAC_32/System.Web/2.0.0.0__b03f5f7f11d50a3a/System.W
eb.dl
l
----------------------------------------
System.Configuration
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.3053 (netfxsp.050727-3000)
    CodeBase: 
file:///C:/Windows/assembly/GAC_MSIL/System.Configuration/2.0.0.0__b03f5f7f11d50
a3a/S
ystem.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.3053 (netfxsp.050727-3000)
    CodeBase: 
file:///C:/Windows/assembly/GAC_MSIL/System.Xml/2.0.0.0__b77a5c561934e089/System
.Xml.
dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

Man, I don't know why I am getting two different types of excecption for two 
different blogs while posting, also I don't know why FeedView control is not 
showing 
the posts of the first blog though it is showing the posts for the second one.

Please help me out and thank you for your patience.


```

Original comment by `anidotNET` on 13 May 2009 at 4:04

**Comment by GoogleCodeExporter** [comment]
```
I am getting the later exception as well, and the reason for this is that 
blogger is not returning the posted 
entry anymore when you create a new entry. The code in the sample does things 
like: 

BloggerEntry entry = Service.insert(someentry)....

so when blogger returns nothing, the code complains. That's easy to fix, but i 
am investigating with blogger 
on why they changed this first. 

The other one, your original post, is a different matter, and i am a tad 
clueless. Did you ask in the blogger 
forum? I am not sure why blogger would return a 405 for anything. If you did 
already ask, please point me to 
the thread, otherwise i am going to investigate inhouse.

Sorry for the slow reply, i have been sick for a while... 
```

Original comment by `fman...@gmail.com` on 13 May 2009 at 4:16

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
I already have posted into blogger forum about this problem and here is the 
link:

http://groups.google.com/group/blogger-help-
publishing/browse_thread/thread/ecebdf2884c3f8a1#

Thank you for your support and help.
```

Original comment by `anidotNET` on 13 May 2009 at 6:29
