### ISSUE TITLE
Execution of authentication request returned unexpected large content 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [WhatSupYap/google-gdata#525]
```
What steps will reproduce the problem?
1.Create an account using Google Apps.
2.Thru code trying to access the calendar for appointments
3.While querying it throws the error :Execution of authentication request 
returned unexpected large content length: 1073

What is the expected output? What do you see instead?
Expected output is calendar Feed data.
It works for normal google accounts but fails for account created thru Google 
Apps with eteh following error: Execution of authentication request returned 
unexpected large content length: 1073
-----------------
Dim URLValue as string = 
"http://www.google.com/calendar/embed?src=test@domain.com&ctz=America/Chicago"
Dim CalendarUserName as string = "test@domain.com"
Dim Password as string= "pass"
Dim MyCalService As New CalendarService("TestCalendarApp")
Dim resultFeed As CalendarFeed
MyCalService.setUserCredentials(CalendarUserName, Password)
Dim calQ As New CalendarQuery
calQ.Uri = New 
Uri("http://www.google.com/calendar/feeds/default/allcalendars/full")
try
resultFeed = MyCalService.Query(calQ)
Catch ex As Exception
' ex.message gives 'Execution of authentication request returned unexpected 
large content length: 1073'
end try
```

Original issue reported on code.google.com by `kris...@koolkoffee.com` on 15 Jul 2011 at 2:13

**Comment by GoogleCodeExporter** [comment]
```
Which version of the .NET client library are you using?
This looks like an old bug that has been fixed.
```

Original comment by `ccherub...@google.com` on 15 Jul 2011 at 9:21

**Comment by GoogleCodeExporter** [comment]
Original comment by `ccherub...@google.com` on 1 Aug 2011 at 6:05
- Changed state: **Obsolete**

**Comment by GoogleCodeExporter** [comment]
```
I have been having this problem for quite a while, though it was working for 
the first couple of months that I had it installed.  I have always been using a 
Google Apps login to sync contacts.
  I have every version of .Net available installed, as well as VS 2008 & VS 2010.  I don't have VB installed, so I can't try the above source but I have debugged the latest source of GoogleContactsSync in SVN (C# project is set to use Framework 2.0) and at line 174 of Syncronizer.cs it throws the same error:
"Error: Execution of authentication request returned unexpected large content 
length: 1073"
Lines of interest:
_googleService = new ContactsService("WebGear.GoogleContactsSync");
_googleService.setUserCredentials(username, password);
_authToken = _googleService.QueryAuthenticationToken();  <<<==Error Thrown

TargetSite:
{System.String QueryAuthToken(Google.GData.Client.GDataCredentials)}
StackTrace:
at Google.GData.Client.GDataGAuthRequest.QueryAuthToken(GDataCredentials gc)
at Google.GData.Client.GDataGAuthRequestFactory.QueryAuthToken(GDataCredentials 
gc)
at Google.GData.Client.Service.QueryAuthenticationToken()
at WebGear.GoogleContactsSync.Syncronizer.LoginToGoogle(String username, String 
password) in 
C:\Projects\gocontactsync\trunk\GoogleContactsSync\Syncronizer.cs:line 174

Google.GData.Client is v2.0.50727 in the solution.  Should I get a newer 
version of the GData Dlls and switch to .Net 3.5 or 4?
  I am Currently just using the code in the SVN project and havn't downloaded any newer bits from Google.

 - Thanks for any advice

```

Original comment by `BraveD...@gmail.com` on 12 Aug 2011 at 5:07

**Comment by GoogleCodeExporter** [comment]
```
Please try downloading the latest source from the repository and rebuild the 
solution, this issue has been fixed a long time ago.
You can target .NET 2.0, our library supports all versions of the Framework 
starting from that.


```

Original comment by `ccherub...@google.com` on 12 Aug 2011 at 5:21

**Comment by GoogleCodeExporter** [comment]
```
Oops, sorry, The version of Google.GData.Client is 1.2.0.0.  Just downloaded 
the 1.8 client and will try using that one.  Sure wish the project had been 
updated in SourceForge in the last two years! 
  - but that is not your problem, I've gotten logged in to Source Forge to see what I can do there.
 - BraveDaun
```

Original comment by `BraveD...@gmail.com` on 12 Aug 2011 at 5:49
