### ISSUE TITLE
Parse error when inserting or updating Google contacts

### ISSUE THREAD

**Issue by GoogleCodeExporter** [WhatSupYap/google-gdata#682]
```
What steps will reproduce the problem?
Parse error when inserting (Google.GData.Client.FeedRequest`1.Insert) or 
updating (Google.GData.Client.FeedRequest`1.Update) Google contacts, see stack 
trace below

What is the expected output? Google contact inserted and updated successfully
What do you see instead? see API Feedback and stack tracke:

<?xml version="1.0" encoding="UTF-8"?>
<errors xmlns="http://schemas.google.com/g/2005">

<error>

<domain>GData</domain>

 <code>parseError</code>

<internalReason>Parse Error</internalReason>

</error>
</errors>
. 

Execution of request failed: 
https://www.google.com/m8/feeds/contacts/default/full
<?xml version="1.0" encoding="utf-8"?>
<entry xmlns="http://www.w3.org/2005/Atom" 
xmlns:gd="http://schemas.google.com/g/2005">
  <gd:name>
    <gd:givenName>test</gd:givenName>
    <gd:fullName>test</gd:fullName>
  </gd:name>
  <gContact:initials xmlns:gContact="http://schemas.google.com/contact/2008">t.</gContact:initials>
  <gContact:groupMembershipInfo href="http://www.google.com/m8/feeds/groups/saller.flo%40gmail.com/base/6" xmlns:gContact="http://schemas.google.com/contact/2008" />
  <gd:extendedProperty name="gos:oid:WorkLaptop" value="000000009AE25C67C3510F488D5FECFDF40D66D80700FEB9354E4637B5408624CC561E7B1185000000BA6C4000003FE340FF7C9C73438F2C7F216FB0BEE200004456B4250000" />
  <title type="text">test</title>
  <category term="http://schemas.google.com/contact/2008#contact" scheme="http://schemas.google.com/g/2005#kind" />
  <content type="text" />
</entry> ---> Google.GData.Client.GDataRequestException: Execution of request 
failed: https://www.google.com/m8/feeds/contacts/default/full ---> 
System.Net.WebException: The remote server returned an error: (400) Bad Request.
   at System.Net.HttpWebRequest.GetResponse()
   at Google.GData.Client.GDataRequest.Execute()
   --- End of inner exception stack trace ---
   at Google.GData.Client.GDataRequest.Execute()
   at Google.GData.Client.GDataGAuthRequest.Execute(Int32 retryCounter)
   at Google.GData.Client.GDataGAuthRequest.Execute()
   at Google.GData.Client.Service.EntrySend(Uri feedUri, AtomBase baseEntry, GDataRequestType type, AsyncSendData data)
   at Google.GData.Client.Service.Insert(Uri feedUri, AtomEntry newEntry, AsyncSendData data)
   at Google.GData.Client.Service.Insert[TEntry](Uri feedUri, TEntry entry)
   at Google.GData.Client.FeedRequest`1.Insert[Y](Uri address, Y entry)


What version of the product are you using? On what operating system?

Latest Google Data API 2.2.0 from June 2013 on Windows7
```

Original issue reported on code.google.com by `Saller....@gmail.com` on 21 Feb 2014 at 8:34

**Comment by GoogleCodeExporter** [comment]
```
Was a Problem on Google side. Since yesterday it seems the Problem is fixed by 
Google (tried it out on my own and got also the Feedback from some users)

You can Close this issue
```

Original comment by `Saller....@gmail.com` on 1 Mar 2014 at 9:39

**Comment by GoogleCodeExporter** [comment]
Original comment by `ccherub...@google.com` on 1 Mar 2014 at 7:40
- Changed state: **ByDesign**

**Comment by GoogleCodeExporter** [comment]
```
We have a Rails app which creates contacts on Google using Contacts API V3 and 
uses it to sync data between google and our app. 

Earlier, we implemented this feature for creating all contact details like 
Name, title, address, phone numbers and email addresses. The creation of 
contacts from our app to Google was working fine. 

Recently, we enhanced this feature to create Groups and assigning them to 
created contacts on Google. But while creating contacts, it is failing with 
error:

<?xml version="1.0" encoding="UTF-8"?> 
<errors xmlns="http://schemas.google.com/g/2005"> 
  <error> 
    <domain>GData</domain> 
    <code>parseError</code> 
    <internalReason>Parse Error</internalReason> 
  </error> 
</errors> (HTTP 400).

We are creating contacts on Google in BATCHES and this is where it is breaking.

Peculiar thing about this issue is that it's inconsistent. Once this error is 
raised for one user, it doesnt comes in picture next time for same user. And we 
cannot debug since we are creating contacts in BATCHES and failure is not 
consistent across user.

Can anyone help us on this issue? Any way to debug what data is causing this 
issue?

Thanks.
```

Original comment by `varunlal...@gmail.com` on 4 Jul 2014 at 12:04
