### ISSUE TITLE
cannot login any more when using the api

### ISSUE THREAD

**Issue by GoogleCodeExporter** [WhatSupYap/google-gdata#703]
```
Hi We have a sync application that connects to google api, it suddenly stoped 
working, i receive this error:

Exception type: GDataRequestException
Exception message: Execution of request failed: 
https://www.google.com/calendar/feeds/default/owncalendars/full
Inner Exception: System.Net.WebException: The remote server returned an error: 
(403) Forbidden.
   at System.Net.HttpWebRequest.GetResponse()
   at Google.GData.Client.GDataRequest.Execute()

--------------------
i tried to enable "Access for less secure apps", but it didn't help either.
we can connect to gmail calendar with the same credentials, please assist.
```

Original issue reported on code.google.com by `adnanra...@gmail.com` on 19 Nov 2014 at 10:26

**Comment by GoogleCodeExporter** [comment]
```
ok, i found in the net that i need to start converting my api intergration to v3
```

Original comment by `adnanra...@gmail.com` on 19 Nov 2014 at 11:12

**Comment by GoogleCodeExporter** [comment]
```
Correct, the Calendar API v2 is deprecated and you need to update to v3, which 
is supported by another set of libraries: 
https://developers.google.com/google-apps/calendar/downloads
```

Original comment by `ccherub...@google.com` on 19 Nov 2014 at 4:21
- Changed state: **ByDesign**

**Comment by GoogleCodeExporter** [comment]
```
thanks
```

Original comment by `adnanra...@gmail.com` on 20 Nov 2014 at 5:46

**Comment by GoogleCodeExporter** [comment]
```
Hi again.

unfortunately, i am unable to connect to my customer's gmail calendar any more 
using the old way, my program is a windows service.

i used your old calendar api 2.2, it was working with google calendar .net 
library using c#.

i used your api's method that called setUserCredential in order to connect, but 
its useless now.

i understand that my only way making it work is to use oAuth2, but how can i 
use it with installed windows service, tried the stream example, it works fine 
with stand alone app, but not on windows service.

this windows service can be installed on a remote server that holds more than 1 
google user, this service will sync our application sql data with these user's 
Calendar on google.

please assist, is there any example, our customers are out of service since 
17/11/2014?
```

Original comment by `adnanra...@gmail.com` on 26 Nov 2014 at 6:33

**Comment by GoogleCodeExporter** [comment]
```
Issue 706 has been merged into this issue.
```

Original comment by `ccherub...@google.com` on 26 Nov 2014 at 6:35

**Comment by GoogleCodeExporter** [comment]
```
thank you for your fast reply, but i am not sure what does that say.

Regards.
```

Original comment by `adnanra...@gmail.com` on 27 Nov 2014 at 7:38

**Comment by GoogleCodeExporter** [comment]
```
I am also facing the same issue. Any answer available for this?
```

Original comment by `calendar...@gmail.com` on 23 Jun 2015 at 4:15
